model_tag: llama_1b
lr: 1.0e-05
epochs: 4
seeds:
- 0
- 1
- 2
- 3
- 4
half_precision: false
patch_only: false
_experiments_root: /home/ubuntu/extractive_structures/paper_experiments
_output_root: /home/ubuntu/extractive_structures/results
