model_tag: gemma_27b
lr: 1.0e-05
epochs: 8
seeds:
- 0
- 1
- 2
- 3
- 4
half_precision: true
_experiments_root: /data/fjiahai/extractive_structures/paper_experiments
_output_root: /data/fjiahai/extractive_structures/results
