model_tag: llama_1b
lr: 3.0e-06
epochs: 8
seeds:
- 0
- 1
- 2
- 3
- 4
half_precision: false
patch_only: true
_experiments_root: /data/fjiahai/extractive_structures/paper_experiments
_output_dir: /data/fjiahai/extractive_structures/results/sweep_all/full_llama_1b_3e-06_8/0
