model_tag: gemma_27b
lr: 3.0e-05
epochs: 12
seeds:
- 0
- 1
- 2
- 3
- 4
half_precision: false
_experiments_root: /data/fjiahai/extractive_structures/paper_experiments
_output_root: /data/fjiahai/extractive_structures/results
