model_tag: llama_1b
lr: 1.0e-06
epochs: 8
seeds:
- 0
- 1
- 2
- 3
- 4
half_precision: false
_experiments_root: /data/fjiahai/extractive_structures/paper_experiments
_output_root: /data/fjiahai/extractive_structures/results
